---
- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
- name: "Install required flatpaks"
  community.general.flatpak:
    method: user
    name: "{{ item }}"
    state: latest
  with_items: "{{ required_flatpaks }}"
