---
- name: "Install zsh as overlay"
  become: true
  community.general.rpm_ostree_pkg:
    name: zsh
    state: present
  register: result

#reboot into the new tree.
- name: reboot os
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 120
  when: result.changed 

- name: change user shell to zsh 
  become: yes
  user:
    name: "{{ main_user }}"
    shell: /bin/zsh

  
- name: "Check if ohmyzsh is already installed"
  ansible.builtin.stat:
    path: "~/.oh-my-zsh/oh-my-zsh.sh"
  register: ohmyzsh_result
- ansible.builtin.debug:
    var: ohmyzsh_result


- name: "Download ohmyzsh install script"
  ansible.builtin.get_url:
    url: "{{ ohmyzsh_install_url }}"
    dest: /tmp/install-omz
  when: ohmyzsh_result.stat.exists == false

- name: "Make install script executable"
  ansible.builtin.file:
    dest: /tmp/install-omz
    mode: a+x
  when: ohmyzsh_result.stat.exists == false
- name: "Install Oh my zsh"
  ansible.builtin.shell:
    cmd: /tmp/install-omz --unattended
  when: ohmyzsh_result.stat.exists == false

- name: "remove autogenerated .zshrc"
  ansible.builtin.file:
    dest: ~/.zshrc
    state: absent
  when: ohmyzsh_result.stat.exists == false
