---
- name: "Configure workstation"
  hosts: workstations
  user: "{{ main_user }}"
  roles:
    - homebrew
    - flatpak
    - kitty
  tasks:
    - name: configure Work VPN
      become: true
      community.general.nmcli:
        type: vpn
        conn_name: UA VPN
        vpn:
          service-type: org.freedesktop.NetworkManager.openconnect
          gateway: vpnmfa.uantwerpen.be
        autoconnect: false
        state: present
